const GraphData = {
  nodes: [
    { id: "Charlotte", group: 1 },
    { id: "Andie", group: 1 },
    { id: "Mari", group: 2 },
    { id: "Jaein", group: 2 },
    { id: "Ari", group: 2 },
    { id: "Electric Scooters", group: 3 },
    { id: "Pepero Bouquet", group: 3 },
    { id: "Pink Dildo", group: 3 },
    { id: "dxyz", group: 4 },
    { id: "Gym", group: 5 },
    { id: "Mexico", group: 4 },
    { id: "UK", group: 4 },
    { id: "Andie's House", group: 4 },
    { id: "Charlotte's House", group: 4 },
    { id: "Bar that smelled old", group: 4 },
    { id: "Jori", group: 4 },
    { id: "Seoul Forrest", group: 4 },
    { id: "Jojo", group: 5 },
    { id: "Catzzz", group: 5 },
    { id: "Girono T-Shirt", group: 3 },
    { id: "Jojo's Calendar", group: 3 },
    { id: "Kuromi Bouquet", group: 3 },
    { id: "Kuromi T-Shirt", group: 3 },
    { id: "Kuromi Socks", group: 3 },
    { id: "Gave each other flowers", group: 6 },
    { id: "Proposal", group: 6 },
    { id: "First Kiss", group: 6 },
    { id: "Charlotte's 21st Birthday", group: 6 },
    { id: "Andie's 22nd Birthday", group: 6 },
    { id: "Sam", group: 2 },
    { id: "Mona", group: 2 },
    { id: "lilac", group: 7 },
    { id: "beige", group: 7 },
    { id: "Song: For Lovers", group: 8 },
    { id: "Cleaning when anxious", group: 5 },
  ],
  links: [
    { source: "Charlotte", target: "Andie", value: 1 },
    { source: "Charlotte", target: "Mari", value: 1 },
    { source: "Andie", target: "Mari", value: 1 },
    { source: "Charlotte", target: "Jaein", value: 1 },
    { source: "Andie", target: "Jaein", value: 1 },
    { source: "Charlotte", target: "Ari", value: 1 },
    { source: "Andie", target: "Ari", value: 1 },
    { source: "Jaein", target: "Mari", value: 1 },
    { source: "Charlotte", target: "Electric Scooters", value: 1 },
    { source: "Charlotte", target: "Pepero Bouquet", value: 1 },
    { source: "Andie", target: "Pepero Bouquet", value: 1 },
    { source: "Charlotte", target: "Pink Dildo", value: 1 },
    { source: "Andie", target: "Pink Dildo", value: 1 },
    { source: "Charlotte", target: "dxyz", value: 1 },
    { source: "Charlotte", target: "Gym", value: 1 },
    { source: "Andie", target: "Gym", value: 1 },
    { source: "Charlotte", target: "Mexico", value: 1 },
    { source: "Andie", target: "UK", value: 1 },
    { source: "Charlotte", target: "Andie's House", value: 1 },
    { source: "Andie", target: "Charlotte's House", value: 1 },
    { source: "Charlotte", target: "Charlotte's House", value: 1 },
    { source: "Andie", target: "Andie's House", value: 1 },
    { source: "Charlotte", target: "Bar that smelled old", value: 1 },
    { source: "Andie", target: "Bar that smelled old", value: 1 },
    { source: "Charlotte", target: "Jori", value: 1 },
    { source: "Andie", target: "Jori", value: 4 },
    { source: "Charlotte", target: "Seoul Forrest", value: 1 },
    { source: "Andie", target: "Seoul Forrest", value: 1 },
    { source: "Charlotte", target: "Jojo", value: 1 },
    { source: "Andie", target: "Jojo", value: 1 },
    { source: "Charlotte", target: "Catzzz", value: 1 },
    { source: "Andie", target: "Catzzz", value: 1 },
    { source: "Charlotte", target: "Girono T-Shirt", value: 1 },
    { source: "Jojo", target: "Girono T-Shirt", value: 1 },
    { source: "Andie", target: "Girono T-Shirt", value: 1 },
    { source: "Charlotte", target: "Jojo's Calendar", value: 1 },
    { source: "Andie", target: "Jojo's Calendar", value: 1 },
    { source: "Jojo", target: "Jojo's Calendar", value: 1 },
    { source: "Charlotte", target: "Kuromi Bouquet", value: 1 },
    { source: "Andie", target: "Kuromi Bouquet", value: 1 },
    { source: "Charlotte", target: "Kuromi T-Shirt", value: 1 },
    { source: "Andie", target: "Kuromi T-Shirt", value: 1 },
    { source: "Charlotte", target: "Kuromi Socks", value: 1 },
    { source: "Kuromi Socks", target: "Andie's 22nd Birthday", value: 1 },
    { source: "Andie", target: "Kuromi Socks", value: 1 },
    { source: "Charlotte", target: "Gave each other flowers", value: 1 },
    { source: "Andie", target: "Gave each other flowers", value: 1 },
    { source: "Charlotte", target: "Proposal", value: 1 },
    { source: "Andie", target: "Proposal", value: 1 },
    { source: "Proposal", target: "First Kiss", value: 1 },
    { source: "Proposal", target: "Gave each other flowers", value: 1 },
    { source: "Charlotte", target: "First Kiss", value: 1 },
    { source: "Andie", target: "First Kiss", value: 1 },
    { source: "Charlotte", target: "Charlotte's 21st Birthday", value: 1 },
    { source: "Andie", target: "Charlotte's 21st Birthday", value: 1 },
    { source: "Pink Dildo", target: "Charlotte's 21st Birthday", value: 1 },
    { source: "Charlotte", target: "Andie's 22nd Birthday", value: 1 },
    { source: "Andie", target: "Andie's 22nd Birthday", value: 1 },
    { source: "Andie", target: "Sam", value: 1 },
    { source: "Charlotte", target: "Mona", value: 1 },
    { source: "Charlotte", target: "lilac", value: 1 },
    { source: "Andie", target: "lilac", value: 1 },
    { source: "Charlotte", target: "beige", value: 1 },
    { source: "Andie", target: "Song: For Lovers", value: 1 },
    { source: "Charlotte", target: "Song: For Lovers", value: 1 },
    { source: "Mari", target: "Catzzz", value: 1 },
    { source: "Ari", target: "Catzzz", value: 1 },
    { source: "Charlotte", target: "Cleaning when anxious", value: 1 },
    { source: "Andie", target: "Cleaning when anxious", value: 1 },
  ],
};

export default GraphData;
